version: '3'
services:
  omnia_feed:
    image: upshot-omnia-feed
    build:
      context: "."
    volumes:
      - "./bin:/opt/omnia/bin"
      - "./lib:/opt/omnia/lib"
      - "./exec:/opt/omnia/exec"
      - "./test:/opt/omnia/test"
      - "../version:/opt/omnia/version"
      - "./config/feed.json:/home/omnia/omnia.json"
      - "./docker/spire/config/feed_config.hcl:/home/omnia/spire.hcl"
      - "./docker/gofer/client.hcl:/home/omnia/gofer.hcl"
      - "./docker/keystore/:/home/omnia/.ethereum/keystore/"
    environment:
      OMNIA_VERBOSE: "true"
      SPIRE_CONFIG: "/home/omnia/spire.hcl"
      CFG_SPIRE_RPC_ADDR: "0.0.0.0:9101"
      GOFER_CONFIG: "/home/omnia/gofer.hcl"
#      OMNIA_DEBUG: "true"
      CFG_ETH_FROM: "0x2d800d93b065ce011af83f316cef9f0d005b0aa4"
      CFG_ETH_KEYS: "/home/omnia/.ethereum/keystore"
      CFG_ETH_PASS: "/home/omnia/.ethereum/keystore/pass"

networks:
  default:
    name: omnia_network
